[build-system]
requires = ["setuptools >= 61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "SVInsight"
version = "0.2.7"
dependencies = [
    "census==0.8.21",
    "factor_analyzer==0.5.1",
    "geopandas==0.14.2",
    "numpy==1.26.4",
    "pandas==2.2.2",
    "PyYAML==6.0.1",
    "scikit_learn==1.3.0"
]
requires-python = ">=3.8"
authors = [
  {name = "Matthew Preisser", email = "mattpreisser@gmail.com"},
]
description = "Create social vulnerabilty index"
readme = "README.rst"
license = {file = "LICENSE.txt"}
keywords = ["SVI"]
classifiers = [
  "Development Status :: 3 - Alpha",
  "Programming Language :: Python"
]

[project.urls]
Homepage = "https://example.com"
Documentation = "https://readthedocs.org"


